-- AlterTable
ALTER TABLE "Area" ADD COLUMN     "order" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "showOnHome" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "type" TEXT NOT NULL DEFAULT 'DISTRICT';
